on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "test"
      - name: Extract tag name
        run: |
          if ${{github.event_name}} != 'pull_request'
          then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=test" >> $GITHUB_ENV
          fi
        id: tag
        
      - name: Print tag name
        run: |
          echo 'The branch name is' $TAG
