on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "test"
      - name: Extract branch name on push
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: Extract branch name on pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> >> $GITHUB_ENV

      - name: Print branch name
        run: |
          echo 'The branch name is' $BRANCH_NAME
