on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "test"
      - name: Get tag on push
        if: github.event_name == 'push'
        run: echo "TAG=latest" >> $GITHUB_ENV
      - name: Get tag on pull_request
        if: github.event_name != 'push'
        run: echo "TAG=test" >> $GITHUB_ENV
      - name: Print tag name
        run: echo 'The tag name is' $TAG
