on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "test"
      - name: Extract tag name on push
        if: github.event_name != 'pull_request'
        run: |
          echo "TAG=latest" >> $GITHUB_ENV
        id: tag

      - name: Extract tag name on pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "TAG=test" >> $GITHUB_ENV

      - name: Print tag name
        run: |
          echo 'The branch name is' $TAG
